import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {createChatReceiver} from '../../soop-chat.js';
function game(n){const c={window:{}};vm.runInNewContext(readFileSync(new URL('../../pinball.js',import.meta.url),'utf8'),c);let seed=123;const rng=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const g=c.window.createPinballGame({roundFace:()=>null});g.reset(Array.from({length:n},(_,i)=>({i,name:`ball ${i}`})),rng);return g;}
for(const n of [2,22,200])test(`${n} marbles launch, remain finite, drain to exactly one winner`,()=>{const g=game(n),dead=new Set();for(let i=0;!g.winner&&i<120*90;i++){for(const m of g.update(1/120)){assert(!dead.has(m.i));dead.add(m.i);}assert(g.balls.every(b=>Number.isFinite(b.x+b.y+b.vx+b.vy)));}assert(g.winner);assert.equal(dead.size,n-1);assert.equal(g.balls.filter(b=>b.alive).length,1);});
test('left flipper strikes a nearby marble upward',()=>{const g=game(2);g.update(.01);Object.assign(g.balls[0],{x:276,y:1012,vx:0,vy:100,cool:0,queued:false,inLane:false});Object.assign(g.balls[1],{x:350,y:245,vx:0,vy:0,queued:false,inLane:false});assert(g.command('!왼'));g.update(1/120);assert(g.balls[0].vy< -500);assert(!g.command('anything'));});
test('simultaneous drain preserves one winner, reset clears result',()=>{const g=game(2);g.update(.1);g.balls.forEach((b,i)=>Object.assign(b,{x:337+i*30,y:1166+i,vy:100,vx:0,queued:false,inLane:false}));assert.equal(g.update(.01).length,1);assert(g.winner);g.reset([{i:0},{i:1}],()=>.5);assert.equal(g.winner,undefined);assert.equal(g.time,0);});
test('SOOP pinball commands deduplicate and stop while paused',()=>{const calls=[];let paused=false;const r=createChatReceiver({game:()=>({mode:'pinball',phase:'battle',paused}),command:t=>{calls.push(t);return true;},show:()=>{},now:()=>100});const e={id:'a',at:100,text:'!왼'};assert(r.receive(e));assert(!r.receive(e));assert(!r.receive({...e,id:'b',text:'hello'}));paused=true;assert(!r.receive({...e,id:'c',text:'!오'}));assert.deepEqual(calls,['!왼']);});

test('every marble starts in the right shooter and exits through the top',()=>{const g=game(22);assert(g.balls.every(b=>b.queued&&b.x===712&&b.y===1040));g.update(.1);const flying=g.balls.filter(b=>!b.queued);assert(flying.length>1);assert(flying.every(b=>b.x>680&&b.vy<0));for(let i=0;i<120*3;i++)g.update(1/120);assert(g.balls.some(b=>!b.inLane&&b.x<656));assert(g.balls.every(b=>!b.queued));});
test('drain is confined to the central chute with closed side aprons',()=>{const g=game(22);const dead=[];for(let i=0;i<120*90&&!g.winner;i++){for(const source of g.update(1/120)){const b=g.balls.find(b=>b.source===source);assert(b.x>315&&b.x<405);assert(b.y>1165);dead.push(source);}}assert.equal(dead.length,21);assert(g.balls.every(b=>b.y<1200));});
